analytics: {}
color:
  brandColors:
    - '#B0B0B0'
    - '#B07818'
    - '#687078'
    - '#E8B840'
    - '#000000'
  brandStrength: 0.75929
  lightness: 0.227941
  rhythmicContrast: 0.758326
  saturation: 0.766413
cta: {}
layout_spectrum: 0.208614
name: test
opengraph: {}
purpose: {}
typography_spectrum: 0.264533
